# action.yml
name: 'concord-action'
description: 'Github action for running concord'
inputs:
  cmd:
    description: 'command to run'
    required: true
    default: help
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}

