# action.yml
name: 'concord-action'
description: 'Github action for running concord'
inputs:
  file:
    description: 'manifest file to use'
    required: false
    default: 'concord.yml'
  cmd:
    description: 'command to run'
    required: true
    default: help
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-f ${{ inputs.file }}"
    - ${{ inputs.cmd }}

