name: Build
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push
      run: |
        docker build -t ghcr.io/gomicro/concord-action .
        docker push ghcr.io/gomicro/concord-action

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ghcr.io/gomicro/concord-action "ghcr.io/gomicro/concord-action:$GITHUB_REF_NAME"
        docker push "ghcr.io/gomicro/concord-action:$GITHUB_REF_NAME"
